version: "3"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9096:9096"
    restart: unless-stopped
    depends_on:
      - db
    networks:
      - backend
  db:
    image: "redis:alpine" 
    restart: unless-stopped
    networks:
      - backend
networks:
  backend:
